final/final/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from accounts import views




urlpatterns = [
    url(r'^accounts/',include('accounts.urls')),
    url(r'^student/',include('student.urls')),
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),


]


if settings.DEBUG:
    urlpatterns +=[
        url(r'^media/(?P<path>.*)$' ,serve,{
            'document_root' : settings.MEDIA_ROOT,
        }),
    ]

final/student/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name='student'

urlpatterns=[
    path('first_page/',views.first_page,name="first_page"),
    path('Second_page/',views.Second_page,name="Second_page"),
    path('Third_page/',views.Third_page,name="Third_page"),
    path('Fourth_page/',views.Fourth_page,name="Fourth_page"),
    path('Student_full_info/',views.Student_full_info,name="Student_full_info"),
    path('Alt_student_full_info/',views.Alt_student_full_info,name="Alt_student_full_info"),
    path('Prob_form/',views.Prob_form,name="Prob_form"),
    path('Contact/',views.Contact,name="Contact"),
    path('home/',views.home,name="home"),
    path('notice/',views.notice,name="notice"),
    path('tnc/',views.tnc,name="tnc"),

]

final/student/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator,MaxValueValidator
from datetime import datetime

# Create your models here.

def user_directory_path(instance,filename):
    return 'user_{id}/{file}'.format(id=instance.user.id ,file=filename)



class Student_form1(models.Model):
    First_name= models.CharField(max_length = 100)
    Middle_name= models.CharField(max_length = 100,blank=True,null=True)
    Last_name = models.CharField(max_length = 100)
    Address = models.CharField(max_length = 100)
    phone_number = models.CharField(max_length=12,unique= True)
    email = models.EmailField(max_length=70,unique= True)
    Nationality = (
        ('India', 'India'),
        ('Foreign', 'Foreign'),
    )
    Nationality = models.CharField(max_length = 7, choices = Nationality)

    STATUS = (
        ('Male', 'Male'),
        ('Female', 'female'),
        ('Other', 'other'),
    )

    Gender = models.CharField(max_length = 6, choices = STATUS)
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username



class Student_form2(models.Model):
    Mother_name= models.CharField(max_length = 100)
    Father_name= models.CharField(max_length = 100)
    marks_in_tenth= models.CharField(max_length = 5)
    tenth_marksheet= models.FileField(null=True,blank=True,upload_to=user_directory_path)
    Status_of_twefth_result= (
        ('Awaited', 'Awaited'),
        ('Passed', 'Passed'),
    )

    Status_of_twefth_result = models.CharField(max_length = 7, choices =Status_of_twefth_result)
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username


class Student_form3(models.Model):
    marks_in_twelfth= models.CharField(max_length = 5)
    Subject1_marks= models.CharField(max_length = 5,blank=True,null=True)
    Subject2_marks= models.CharField(max_length = 5,blank=True,null=True)
    Subject3_marks= models.CharField(max_length = 5,blank=True,null=True)
    Subject4_marks= models.CharField(max_length = 5,blank=True,null=True)
    twelfth_marksheet= models.FileField(null=True,blank=True,upload_to=user_directory_path)
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username






class Student_form4(models.Model):
    candidate_photo= models.ImageField(null=True,blank=True,upload_to=user_directory_path)
    thumb_impression= models.ImageField(null=True,blank=True,upload_to=user_directory_path)
    candidate_signature= models.ImageField(null=True,blank=True,upload_to=user_directory_path)
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username
    







class Prob_form(models.Model):
    Name= models.CharField(max_length = 100,blank=True)
    Subject= models.CharField(max_length = 200,blank=True)
    Description= models.CharField(max_length = 500,blank=True)
    Error_number= models.CharField(max_length = 5,blank=True)
    def __str__(self):
            return self.Name

final/student/forms.py
from django import forms
from . import models

class Stuform1(forms.ModelForm):
    class Meta:
        model = models.Student_form1
        fields ='__all__'
        exclude =['user',]
    

class Stuform2(forms.ModelForm):
    class Meta:
        model = models.Student_form2
        fields ='__all__'
        exclude =['user',]

class Stuform3(forms.ModelForm):
    class Meta:
        model = models.Student_form3
        fields ='__all__'
        exclude =['user',]

class Stuform4(forms.ModelForm):
    class Meta:
        model = models.Student_form4
        fields ='__all__'
        exclude =['user',]

class Prob_form(forms.ModelForm):
    class Meta:
        model = models.Prob_form
        fields ='__all__'







        

final/student/views.py
from django.shortcuts import render,redirect
from django.conf import settings
from django.http import HttpResponse
from . import forms
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Student_form1,Student_form2,Student_form3,Student_form4
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist



# Create your views here.
@login_required(login_url="/accounts/login")
def first_page(request):

    if request.method == 'GET':
        try:
            status=request.user.student_form1.First_name
            if status!=None:
                return redirect('student:Second_page') 
        except ObjectDoesNotExist as e:
            form=forms.Stuform1()

    else:
        form=forms.Stuform1(request.POST,request.FILES)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.user=request.user
            obj.save()
            return redirect('student:Second_page')
    context ={
        'stu_form1':form
    }
    return render(request,'first_page.html',context)

@login_required(login_url="/accounts/login")
def Second_page(request):
    if request.method == 'GET':
        try:
            status=request.user.student_form2.Mother_name
            if status!=None:
                if status=="Awaited":
                    return redirect('student:Fourth_page') 
                else:
                    return redirect('student:Third_page') 
        except ObjectDoesNotExist as e:
            form=forms.Stuform2() 
    else:
        form=forms.Stuform2(request.POST)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.user=request.user
            obj.save()
            status=request.user.student_form2.Status_of_twefth_result
            if status=="Awaited":
                return redirect('student:Fourth_page') 
                 
            else:
                return redirect('student:Third_page') 
               
    context ={
        'stu_form2':form
    }
    return render(request,'Second_page.html',context)

@login_required(login_url="/accounts/login")
def Third_page(request):
    if request.method == 'GET':
        try:
            status=request.user.student_form3.Subject1_marks
            if status!=None:
                return redirect('student:Fourth_page') 
        except ObjectDoesNotExist as e:
            form=forms.Stuform3()
    else:
        form=forms.Stuform3(request.POST)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.user=request.user
            obj.save()
            return redirect('student:Fourth_page')
    context ={
        'stu_form3':form
    }
    return render(request,'Third_page.html',context)



@login_required(login_url="/accounts/login")
def Fourth_page(request):
    if request.method == 'GET':
        try:
            status=request.user.student_form4.candidate_photo
            if status!=None:
                status_1=request.user.student_form2.Status_of_twefth_result
                if status_1=="Awaited":
                    return redirect('student:Student_full_info') 
                else:
                    return redirect('student:Alt_student_full_info') 
        except ObjectDoesNotExist as e:
            form=forms.Stuform4()
    else:
        form=forms.Stuform4(request.POST)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.user=request.user
            obj.save()
            status_1=request.user.student_form2.Status_of_twefth_result
            if status_1=="Awaited":
                return redirect('student:Student_full_info') 
            else:
                return redirect('student:Alt_student_full_info') 
            
    context ={
        'stu_form4':form
    }
    return render(request,'Fourth_page.html',context)





@login_required(login_url="/accounts/login")
def Student_full_info(request):

    args = {'user': request.user}
    return render(request, 'Student_full_info.html',args) 
    if request.method == 'GET':
        HttpResponse("thank you")

@login_required(login_url="/accounts/login")
def Alt_student_full_info(request):
    args = {'user': request.user}
    return render(request, 'Alt_student_full_info.html',args) 

        


def Prob_form(request):
    if request.method == 'GET':
        form=forms.Prob_form()
    else:
        form=forms.Prob_form(request.POST)

        if form.is_valid():
            obj = form.save()
            return HttpResponse("hello")
    context ={
        'Prob_form':form
    }
    return render(request,'Prob_form.html',context)
    
    


def Contact(request):
    if request.method =="GET":
        return render(request,'Contact.html')

def edit(request, user):
    user=request.user
    rest=get_object_or_404(models.student_form1 ,user)
    if request.method == 'GET':
        form=rest
    else:
        form=rest

        if form.is_valid():
            obj = form.save(commit=False)
            obj.user=request.user
            obj.save()
            return HttpResponse("hello")
    context ={
        'rest':form
    }
    return render(request,'first_page.html',context)



def home(request):
    if request.method =="GET":
        args={'user':request.user}
        return render(request, 'home.html',args) 

def notice(request):
    if request.method =="GET":
        args={'user':request.user}
        return render(request, 'notice.html',args) 

    
def tnc(request):
    if request.method=='GET':   
        context ={}
        return render(request,'tnc.html',context)







 

final/student/templates/Alt_student_full_info.html
{% extends 'base_layout.html' %}
{%block content%}

<body>
    <div class="container">
        <p>First name: {{user.student_form1.First_name}}</p><br>
        <p>middle name: {{user.student_form1.Middle_name}}</p><br>
        <p>Last name: {{user.student_form1.Last_name}}</p><br>
        <p>Address: {{user.student_form1.Address}}</p><br>
        <p>phone_number: {{user.student_form1.phone_number}}</p><br>
        <p>email: {{user.student_form1.email}}</p><br>
        <p>Nationality: {{user.student_form1.Nationality}}</p><br>
        <p>Gender: {{user.student_form1.Gender}}</p><br>
        <p>Mother name: {{user.student_form2.Mother_name}}</p><br>
        <p>Father name: {{user.student_form2.Father_name}}</p><br>
        <p>tenth marks: {{user.student_form2.tenth_marks}}</p><br>
        <p>Status_of_twefth_result : {{user.student_form2.Status_of_twefth_result}}</p><br>
        <p>Twelfth_marks: {{user.student_form3.marks_in_twelfth}}</p><br>
        <p>Subject1_marks: {{user.student_form3.Subject1_marks}}</p><br>
        <p>Subject2_marks: {{user.student_form3.Subject2_marks}}</p><br>
        <p>Subject3_marks: {{user.student_form3.Subject3_marks}}</p><br>
        <p>Subject4_marks: {{user.student_form3.Subject4_marks}}</p><br>
        <p>candidate_photo: <img src="{{user.student_form4.candidate_photo.url}}" width="120" height="120" > </p>
        <p>thumb_photo: <img src="{{user.student_form4.thumb_impression.url}}" width="120" height="120" > </p>
        <p>signature_photo: <img src="{{user.student_form4.candidate_signature.url}}" width="120" height="120"> </p>


   

    <input type="checkbox" name="terms" id="terms">
    I have read the <a href="{%url 'student:tnc'%}" target="_blank">
        terms and conditions</a> and i understand that this information is final and cannot be changed.
    <input type="submit"  class="inputButton btn btn-default button12" id="send" value="submit"  data-toggle="tooltip" data-placement="bottom" title="Check the checkbox">
    <br><br><br><br>
  
  </div>
  
  <script type="text/javascript">
  var button=$('#send');
   button.attr('disabled','disabled');
   $('#terms').change(function(e){
     if (this.checked){
       button.removeAttr('disabled');
     }
      else{
        button.attr('disabled','disabled');
      }
     
  
   });
  </script>
</body>
   





{% endblock %}

final/student/templates/Contact.html
{%block content%}


   
<body>
 <div class="container" align="center">
 <h1>Contact Details</h1>
 <label>Name: Abhishek Kataria
 </label><br>
 <label>Contact Number:8285261452
</label><br>
<label>Email:abhishekkataria780@gmail.com</label><br>
<label>Address:236 Bharat Nagar Delhi-52</label><br>
</body>
</div>


{% endblock %}

final/student/templates/Fourth_page.html
{% extends 'base_layout.html' %}
{%block content%}


   
<body>
 
<form class="container" action="" method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    {{ stu_form4.as_p }}
    <input type="checkbox" name="terms" id="terms">
    I have read the <a href="{%url 'student:tnc'%}" target="_blank">
        terms and conditions</a> and i understand that this information is final and cannot be changed.
    <input type="submit"  class="inputButton btn btn-default button12" id="send" value="NEXT" data-toggle="tooltip" data-placement="bottom" title="Check the checkbox">
  
  
  
  

</form>
<script type="text/javascript">
  var button=$('#send');
   button.attr('disabled','disabled');
   $('#terms').change(function(e){
     if (this.checked){
       button.removeAttr('disabled');
     }
      else{
        button.attr('disabled','disabled');
      }
     
  
   });
  </script>
<br><br><br><br>
</body>


{% endblock %}

final/student/templates/Prob_form.html
{% extends 'base_layout.html' %}
{%block content%}


   
<body>
  <h1>Problem</h1>
 
<form class="container" action="" method="POST">
  {%csrf_token%}
  {{ Prob_form.as_p }}
  <button class="btn btn-default button12" type="submit">NEXT</button>
</form>
<br><br><br><br>
</body>


{% endblock %}

final/student/templates/Second_page.html
{% extends 'base_layout.html' %}
{%block content%}


   
<body>
 
<form class="container" action="" method="POST" enctype="multipart/form-data">
  {%csrf_token%}
  {{ stu_form2.as_p }}
  <input type="checkbox" name="terms" id="terms">
  i have read the <a href="{%url 'student:tnc'%}">terms and conditions</a> and i understand that this information is final and cannot be changed.
  <input type="submit"  class="inputButton btn btn-default button12" id="send" value="NEXT" data-toggle="tooltip" data-placement="bottom" title="Check the checkbox">




<script type="text/javascript">
var button=$('#send');
 button.attr('disabled','disabled');
 $('#terms').change(function(e){
   if (this.checked){
     button.removeAttr('disabled');
   }
    else{
      button.attr('disabled','disabled');
    }
   

 });
</script>
  
</form>
<br><br><br><br>
</body>


{% endblock %}

final/student/templates/Student_full_info.html
{% extends 'base_layout.html' %}
{%block content%}

<body>
    <div class="container">
        <p>First name: {{user.student_form1.First_name}}</p><br>
        <p>middle name: {{user.student_form1.Middle_name}}</p><br>
        <p>Last name: {{user.student_form1.Last_name}}</p><br>
        <p>Address: {{user.student_form1.Address}}</p><br>
        <p>phone_number: {{user.student_form1.phone_number}}</p><br>
        <p>email: {{user.student_form1.email}}</p><br>
        <p>Nationality: {{user.student_form1.Nationality}}</p><br>
        <p>Gender: {{user.student_form1.Gender}}</p><br>
        <p>Mother name: {{user.student_form2.Mother_name}}</p><br>
        <p>Father name: {{user.student_form2.Father_name}}</p><br>
        <p>tenth marks: {{user.student_form2.tenth_marks}}</p><br>
        <p>Status_of_twefth_result: {{user.student_form2.Status_of_twefth_result}}</p><br>
        <p>candidate_photo: <img src="{{user.student_form4.candidate_photo.url}}" width="120" height="120"> </p>
        <p>thumb_photo: <img src="{{user.student_form4.thumb_impression.url}}"width="120" height="120" > </p>
        <p>signature_photo: <img src="{{user.student_form4.candidate_signature.url}}"width="120" height="120" > </p>



    </div>

    <input type="checkbox" name="terms" id="terms">
    I have read the <a href="{%url 'student:tnc'%}" target="_blank">
        terms and conditions</a> and i understand that this information is final and cannot be changed.
    <br><br><br>
    <input type="submit"  class="inputButton btn btn-default button12" id="send" value="submit" data-toggle="tooltip" data-placement="bottom" title="Check the checkbox">
    <br><br><br><br>
  
  
  
  
  <script type="text/javascript">
  var button=$('#send');
   button.attr('disabled','disabled');
   $('#terms').change(function(e){
     if (this.checked){
       button.removeAttr('disabled');
     }
      else{
        button.attr('disabled','disabled');
      }
     
  
   });
  </script>
  <br><br><br><br>
</body>
   





{% endblock %}

final/student/templates/Third_page.html
{% extends 'base_layout.html' %}
{%block content%}


   
<body>
 
<form class="container" action="" method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    {{ stu_form3.as_p }}
    <input type="checkbox" name="terms" id="terms">
    i have read the <a href="{%url 'student:tnc'%}">terms and conditions</a> and i understand that this information is final and cannot be changed.
  
    <input type="submit"  class="inputButton btn btn-default button12" id="send" value="NEXT"  data-toggle="tooltip" data-placement="bottom" title="Check the checkbox">
  
  
  
  
  
</form>
<br><br><br><br>
<script type="text/javascript">
  var button=$('#send');
   button.attr('disabled','disabled');
   $('#terms').change(function(e){
     if (this.checked){
       button.removeAttr('disabled');
     }
      else{
        button.attr('disabled','disabled');
      }
     
  
   });
  </script>
</body>


{% endblock %}

final/student/templates/final_page.html
{% extends 'base_layout.html' %}
{%block content%}

<body>
    <div class="container">
        <p>First name: {{user.student_form1.First_name}}</p><br>
        <p>Last name: {{user.student_form1.Last_name}}</p><br>
        <p>phone_number: {{user.student_form1.phone_number}}</p><br>
        <p>email: {{user.student_form1.email}}</p><br>
        <p>Twelfth_marks: {{user.student_form4.ref_id}}</p><br>


   


</body>
   





{% endblock %}

final/student/templates/first_page.html
{% extends 'base_layout.html' %}
{%block content%}


   
<body>
 
<form class="container" action="" method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    {{ stu_form1.as_p }}
    <input type="checkbox" name="terms" id="terms">
    I have read the <a href="{%url 'student:tnc'%}" target="_blank">
        terms and conditions</a> and i understand that this information is final and cannot be changed.
    <input type="submit"  class="inputButton btn btn-default button12" id="send" value="NEXT"  data-toggle="tooltip" data-placement="bottom" title="Check the checkbox">
  
  
  
  

</form>
<script type="text/javascript">
  var button=$('#send');
   button.attr('disabled','disabled');
   $('#terms').change(function(e){
     if (this.checked){
       button.removeAttr('disabled');
     }
      else{
        button.attr('disabled','disabled');
      }
     
  
   });
  </script>
<br><br><br><br>
</body>


{% endblock %}

final/student/templates/home.html
{% extends 'base_layout.html' %}


{%block content%}
<title>Profile</title>
<style>
    div.fixed {
        position: fixed;
        bottom: 40;
        right: 0;
        width: 200px;
        height: 300px;
        border: 3px solid #73AD21;
    }
    </style>

<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
</div>
<div class="fixed">
    <marquee  behavior="scroll" direction="up" scrollamount="2" onmouseover="this.stop()" onmouseout="this.start()"> 
        <ul>
            <li><a href="">NOTICE1</a></li>
            <li><a href="">NOTICE2</a></li>
            <li><a href="">NOTICE3</a></li>
            <li><a href="">NOTICE4</a></li>
        </ul>
    </marquee> 
</div>
<br><br><br><br>

{% endblock %}

final/student/templates/notice.html
{% extends 'base_layout.html' %}
{%block content%}
<body><div id="content">


<table>


        <tr>
          <th>Title</th>
          <th>Date</th>
          <th>File</th>
        </tr>
        <tr>
          <td><a href="">NOTICE1</a></td>
          <td>09/09/2018</td>
          <td>PDF</td>
        </tr>

      </table>
      </div>
      </body>
      <div align="center">
          <a href="#content">TOP ⬆ ️</a> 
      </div>

      {% endblock %}

final/student/templates/tnc.html
{% extends 'base_layout.html' %}
{%block content%}

<h1>TERMS AND CONDITIONS</h1>
      {% endblock %}