final/accounts/urls.py
from django.conf.urls import url
from .import views
from django.urls import path
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete
app_name='accounts'

urlpatterns=[
    
    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout"),
    url(r'^change-password/$', views.change_password, name='change_password'),
   

    url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),

]

final/final/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from accounts import views




urlpatterns = [
    url(r'^accounts/',include('accounts.urls')),
    url(r'^student/',include('student.urls')),
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),


]


if settings.DEBUG:
    urlpatterns +=[
        url(r'^media/(?P<path>.*)$' ,serve,{
            'document_root' : settings.MEDIA_ROOT,
        }),
    ]

final/accounts/models.py
from django.db import models

# Create your models here.

final/accounts/forms.py
from django import forms
from . import models



from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm




class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

final/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,PasswordChangeForm
from django.contrib.auth import login,logout
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from accounts.forms import RegistrationForm
from django.core.mail import send_mail
from django.conf import settings
# Create your views here.
def index(request):
    if request.method=='GET':   
        context ={}
        return render(request,'accounts/index.html',context)


def signup_view(request):
    if request.method =='POST':
        form=RegistrationForm(request.POST)
        if form.is_valid():
            user=form.save()
            subject="thank you"
            message="welcome to student registration"
            from_email = settings.EMAIL_HOST_USER
            to_list=[user.email,settings.EMAIL_HOST_USER ]
            send_mail(subject,message,from_email,to_list,fail_silently=True)
            #login
            login(request,user)
            return redirect('student:home')
    else:
        form=RegistrationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method =='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            return redirect('student:home')
    else:
        form =AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

@login_required(login_url="/accounts/login")
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('student:home'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)
    




def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')

final/templates/accounts/change_password.html
{% extends 'base_layout.html' %}
{%block content%}
<h1>Password Change</h1>
    <form class="container" action="{%url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-default button12" type="submit" >change password</button>
    </form>
{% endblock %}

final/templates/accounts/index.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/my.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    {%block content%}
    <div class="wrapper">
        <h1>WELCOME TO STUDENT REGISTRATION FORM</h1>
    </div>

    <form class="container" action="{%url 'accounts:login'%}" method="GET">
        {% csrf_token %}
        <div class="wrapper">
            <button class="btn btn-default button12 button10" type="submit">LOGIN</button>
        </div>
    </form>

    <form class="container" action="{%url 'accounts:signup'%}" method="GET">
        {% csrf_token %}
        <div class="wrapper">
            <button class="btn btn-default button12 button11" type="submit">SIGNUP</button>
        </div>






     

    {% endblock %}

</body>

final/templates/accounts/login.html
{% extends 'base_layout.html' %}
{%block content%}
    <h1>LOGIN</h1>
        <form class="container" action="{%url 'accounts:login' %}" method="post">
            {% csrf_token %}
            {{form.as_p}}

            <button class="btn btn-default button12" type="submit" >LOGIN</button>
            <small>
                    <a href="{% url 'accounts:reset_password'%}">FORGOT PASSWORD</a>
            </small>

        </form>
        <br>
        <form class="container" action="/accounts/signup/" method="GET">
            {% csrf_token %}

            <button class="btn btn-default button12" type="submit">SIGNUP</button>
        </form>

</body>

{% endblock %}

final/templates/accounts/reset_password.html
{% extends 'base_layout.html' %}

{%block content%}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

final/templates/accounts/reset_password_complete.html
{% extends 'base_layout.html' %}

{%block content%}
<div class="container">
    <h1>Password reset complete</h1>
    <a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock %}

final/templates/accounts/reset_password_confirm.html
{% extends 'base_layout.html' %}

{%block content%}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

final/templates/accounts/reset_password_done.html
{% extends 'base_layout.html' %}

{%block content%}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

final/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

final/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{%block content%}
<h1>signup</h1>
    <form class="container" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-default button12" type="submit">SIGNUP</button>
    </form>
{% endblock %}