final/accounts/urls.py
from django.conf.urls import url
from .import views
from django.urls import path
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete
app_name='accounts'

urlpatterns=[
    
    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout"),
    url(r'^change-password/$', views.change_password, name='change_password'),
   

    url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),

]

final/final/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from accounts import views




urlpatterns = [
    url(r'^accounts/',include('accounts.urls')),
    url(r'^student/',include('student.urls')),
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),


]


if settings.DEBUG:
    urlpatterns +=[
        url(r'^media/(?P<path>.*)$' ,serve,{
            'document_root' : settings.MEDIA_ROOT,
        }),
    ]

final/student/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name='student'

urlpatterns=[
    path('first_page/',views.first_page,name="first_page"),
    path('Second_page/',views.Second_page,name="Second_page"),
    path('Third_page/',views.Third_page,name="Third_page"),
    path('Fourth_page/',views.Fourth_page,name="Fourth_page"),
    path('Student_full_info/',views.Student_full_info,name="Student_full_info"),
    path('Alt_student_full_info/',views.Alt_student_full_info,name="Alt_student_full_info"),
    path('Prob_form/',views.Prob_form,name="Prob_form"),
    path('Contact/',views.Contact,name="Contact"),
    path('home/',views.home,name="home"),
    path('notice/',views.notice,name="notice"),
    path('tnc/',views.tnc,name="tnc"),

]

final/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/my.css' %}">


    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/my.js' %}"></script>
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>

</head>
<body>
    
    <font size="+4"> 
        <font color="black"> 
            <marquee bgcolor= #7700ff direction="LEFT" onmouseover="this.stop()" onmouseout="this.start()">  
            Last date for submission of form is 18.10.2018 and no form will be accepted after due date.  List for admission will be displayed on site on 10.11.2018.    
            </marquee> 
        </font>
    </font>
    <div class="watermark"></div>

    <nav class="navbar navbar-expand-lg navbar-light rounded div1">


            <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <form class="logout-link" action="{%url 'student:home'%}" method="get">
                                {% csrf_token %}
                                <button class="btn btn-default button12" type="submit">HOME </button>
                            </form>
                        </li>  
              
                    </ul>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                  <li>
                        <form class="logout-link" action="{%url 'accounts:change_password'%}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-default button12" type="submit">  Change Password  </button>
                        </form>
                  </li>  

              </ul>
            </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <form class="logout-link" action="{%url 'student:notice'%}" method="get">
                        {% csrf_token %}
                        <button class="btn btn-default button12" type="submit">NOTICE</button>
                    </form>
                </li>  
      
            </ul>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <form class="logout-link" action="{%url 'student:first_page'%}" method="GET">
                            {% csrf_token %}
                            <button class="btn btn-default button12" type="submit"> Fill Forms</button>
                        </form>
                    </li>  
          
                </ul>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <form class="logout-link" action="{%url 'student:Alt_student_full_info'%}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-default button12" type="submit"> Review Information</button>
                        </form>
                    </li>  
          
                </ul>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <form class="logout-link" action="{%url 'accounts:logout'%}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-default button12" type="submit">LOGOUT </button>
                        </form>
                    </li>  
          
                </ul>
        </div>

    </nav>
        {%block content%}
        {% endblock %}



</body>
<div id="footer"  align="center">
                    
    <p >ABHISHEK KATARIA@Django 2018(C) <br>
        <a href="{% url 'student:Prob_form'%}">Report A Problem &nbsp</a><br>
        <a href="{% url 'student:Contact'%}">Contact Details</a>
    </p>
    
</div><br>
</html>